name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Build Docker image
      run: docker build -t brighton-spaces:latest .

  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Railway
      uses: railwayapp/railway-deploy@v3
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: brighton-spaces